name: Run clang-format Linter

on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch


    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        style: file
        source: '.'
        exclude: '**/vendor'
        extensions: 'cpp,hpp'
        clangFormatVersion: 14
        inplace: True
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.1.1
      with: 
        token: ${{ secrets.PAT }}
        commit-message: Clang formatted
        delete-branch: true
        push-to-fork: ItsRainyMonster/DestinyEngine-workflow-pull-requests
        title: Clang Format
        body: Formatted code using Clang Format
        base: ${{ steps.extract_branch.outputs.branch }}
